library(lubridate)
library(plyr)

power <- read.table("household_power_consumption.txt", sep = ";", header = T, stringsAsFactors = F, na.strings = "?")
power <- mutate(power, Date = dmy(Date))
power <- filter(power, Date == ymd("2007-02-01") | Date == ymd("2007-02-02"))
power <- mutate(power, DateTime = paste(Date, Time, sep = "-"), type="o")
power <- mutate(power, DateTimeObject = ymd_hms(DateTime), type="o")
power <- mutate(power, DateTimeSeconds = unclass(as.POSIXct(DateTimeObject)))

min <- min(power$DateTimeSeconds)
max <- max(power$DateTimeSeconds)
fri <- min +  ((max - min) / 2)
par(mfrow = c(2,2), oma = c(2,0,0,0), mar = c(4,4,4,2), bg = "transparent")
par(xaxt = "n")
plot(power$DateTimeSeconds, y = power$Global_active_power, type = "l", pch = 20, xlim = c(min, max), ylab = "Global Active Power", xlab = "")
par(xaxt = "l")
axis(1, labels = c("Thu", "Fri", "Sat"), at = c(min, fri, max), tick = T)

par(xaxt = "n")
plot(power$DateTimeSeconds, y = power$Voltage, type = "l", pch = 20, xlim = c(min, max), ylab = "Voltage", xlab = "")
par(xaxt = "l")
axis(1, labels = c("Thu", "Fri", "Sat"), at = c(min, fri, max), tick = T)
mtext("datetime", 1, padj = 3.5)

par(xaxt = "n")
plot(power$DateTimeSeconds, y = power$Sub_metering_1, type = "l", pch = 20, xlim = c(min, max), ylab = "Energy sub metering", xlab = "")
lines(power$DateTimeSeconds, y = power$Sub_metering_2, col = "red")
lines(power$DateTimeSeconds, y = power$Sub_metering_3, col = "blue")

width = strwidth("Sub_metered_1") * 3.5
legend("topright",box.lwd = 0, y.intersp = 2, legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black", "red", "blue"), lwd = 1, text.width = width)
par(xaxt = "l")
axis(1, labels = c("Thu", "Fri", "Sat"), at = c(min, fri, max), tick = T)

par(xaxt = "n")
plot(power$DateTimeSeconds, y = power$Global_reactive_power, type = "l", pch = 20, xlim = c(min, max), ylab = "Global_reactive_power", xlab = "")
par(xaxt = "l")
axis(1, labels = c("Thu", "Fri", "Sat"), at = c(min, fri, max), tick = T)
mtext("datetime", 1, padj = 3.5)

screen <- dev.cur()
png(width = 480, height = 480, filename = "plot4.png")
png <- dev.cur()
dev.set(screen)
dev.copy(which = png)
dev.off(which = png)